default: &default
  connection: 'amqp://guest:guest@localhost:5672' # TODO: Break these up?
  exchange: backlogg.api.users
  queues:
    all: backlogg.api.users.*
    create: backlogg.api.users.create
    destroy: backlogg.api.users.destroy
    index: backlogg.api.users.index
    show: backlogg.api.users.show
    update: backlogg.api.users.update

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
